plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ultraclone.pro'
    compileSdk 33

    defaultConfig {
        applicationId "com.ultraclone.pro"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
